In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

## Create and Read

#### 1D Array

In [3]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.shape

(5,)

In [6]:
arr1.dtype

dtype('int64')

In [7]:
arr1.ndim

1

In [8]:
arr1.size

5

#### 2D Array

In [9]:
arr2 = np.array([[1,4,5], [6,7,4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [10]:
arr2.ndim

2

In [11]:
arr2.shape # (row, col)

(2, 3)

In [12]:
arr2.dtype

dtype('int64')

In [13]:
arr2.size

6

#### 3D Array

In [14]:
arr3 = np.array([[[1,4,5], [6,7,4]], [[6,2,9], [9,1,4]], [[2,9,3], [1,8,8]]])
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[6, 2, 9],
        [9, 1, 4]],

       [[2, 9, 3],
        [1, 8, 8]]])

In [15]:
arr3.ndim

3

In [16]:
arr3.shape

(3, 2, 3)

In [17]:
arr3.size

18

#### Create random array

In [18]:
randomArr = np.random.rand(3, 2, 3)
randomArr

array([[[0.82260291, 0.81767349, 0.84201052],
        [0.05353169, 0.22654748, 0.64625615]],

       [[0.03799753, 0.86843436, 0.46525845],
        [0.84039783, 0.67362443, 0.15430079]],

       [[0.10051879, 0.0411601 , 0.77519542],
        [0.24530909, 0.91491258, 0.33541839]]])

In [19]:
randomArr.dtype

dtype('float64')

In [27]:
zeroes = np.zeros((3, 2, 3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [28]:
zeroes.ndim

3

In [31]:
full = np.full((3, 2, 3), 9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [33]:
ones = np.ones((3, 2, 3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [34]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[6, 2, 9],
        [9, 1, 4]],

       [[2, 9, 3],
        [1, 8, 8]]])

In [38]:
arr3[0][1][1]

np.int64(7)

In [39]:
arr3[0:2]

array([[[1, 4, 5],
        [6, 7, 4]],

       [[6, 2, 9],
        [9, 1, 4]]])

In [41]:
arr3[0:3]

array([[[1, 4, 5],
        [6, 7, 4]],

       [[6, 2, 9],
        [9, 1, 4]],

       [[2, 9, 3],
        [1, 8, 8]]])

In [42]:
arr3[-1]

array([[2, 9, 3],
       [1, 8, 8]])

In [43]:
arr3[1][0][1]

np.int64(2)

In [44]:
arr3[1, 0, 1]

np.int64(2)

#### Update and Delete

In [45]:
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)

In [46]:
a1

array([[[0.8146221 , 0.33007521],
        [0.47806225, 0.09810377],
        [0.15361281, 0.88779337]],

       [[0.83829739, 0.54463128],
        [0.53259929, 0.13886476],
        [0.38769502, 0.36866977]]])

In [47]:
a2

array([[[0.23590928, 0.95387966],
        [0.34840328, 0.34717277],
        [0.90206686, 0.80678508]],

       [[0.88088763, 0.65921469],
        [0.49701619, 0.14506689],
        [0.10746674, 0.09154317]]])

#### Basic Math Operations

In [48]:
np.add(a1, a2)

array([[[1.05053138, 1.28395487],
        [0.82646553, 0.44527654],
        [1.05567967, 1.69457846]],

       [[1.71918502, 1.20384597],
        [1.02961548, 0.28393165],
        [0.49516175, 0.46021295]]])

In [54]:
np.subtract(a1, a2)

array([[[ 0.57871282, -0.62380445],
        [ 0.12965897, -0.24906899],
        [-0.74845405,  0.08100829]],

       [[-0.04259024, -0.11458341],
        [ 0.0355831 , -0.00620213],
        [ 0.28022828,  0.2771266 ]]])

In [55]:
np.divide(a1, a2)

array([[[3.45311598, 0.34603443],
        [1.37215197, 0.28257912],
        [0.17028983, 1.10040876]],

       [[0.95165076, 0.82618195],
        [1.07159345, 0.95724642],
        [3.60758149, 4.02727772]]])

In [56]:
np.multiply(a1, a2)

array([[[0.19217691, 0.31485203],
        [0.16655846, 0.03405896],
        [0.13856903, 0.71625845]],

       [[0.7384458 , 0.35902894],
        [0.26471047, 0.02014468],
        [0.04166432, 0.0337492 ]]])

#### Statistical Operations

In [67]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
maxs  = np.max(a2)

In [61]:
sqrt

np.float64(5.0)

In [62]:
abs

np.int64(2)

In [63]:
power

np.int64(256)

In [64]:
log

np.float64(3.2188758248682006)

In [65]:
mins

np.float64(0.09810377487419908)

In [68]:
maxs

np.float64(0.9538796621460867)

#### Update

In [69]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[6, 2, 9],
        [9, 1, 4]],

       [[2, 9, 3],
        [1, 8, 8]]])

In [71]:
arr3[0, 0, 2] = 9

In [72]:
arr3

array([[[1, 4, 9],
        [6, 7, 4]],

       [[6, 2, 9],
        [9, 1, 4]],

       [[2, 9, 3],
        [1, 8, 8]]])

In [73]:
arr3.sort()
arr3

array([[[1, 4, 9],
        [4, 6, 7]],

       [[2, 6, 9],
        [1, 4, 9]],

       [[2, 3, 9],
        [1, 8, 8]]])

In [74]:
# Reshape
arr3.shape

(3, 2, 3)

In [77]:
arr3_reshape = arr3.reshape((2, 3, -1))
arr3_reshape

array([[[1, 4, 9],
        [4, 6, 7],
        [2, 6, 9]],

       [[1, 4, 9],
        [2, 3, 9],
        [1, 8, 8]]])

#### Append and Insert

In [78]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [79]:
# Create a new array
new_arr = np.ones((3, 2, 3))
new_arr

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [83]:
# Append
appd = np.append(zeroes, new_arr, axis=0) # axis 0 is row, axis 1 is column
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [84]:
# Insert
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [85]:
new_arr

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [86]:
inserted_arr = np.insert(zeroes, 1, new_arr, axis=0)
inserted_arr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

#### Delete

In [87]:
arr4 = np.random.rand(3, 2, 3)
arr4

array([[[0.97666541, 0.17826285, 0.72274977],
        [0.15947197, 0.17864396, 0.1677207 ]],

       [[0.76291325, 0.26251633, 0.32481159],
        [0.02734588, 0.70156857, 0.28947575]],

       [[0.77360357, 0.97173971, 0.89053621],
        [0.57935893, 0.43655231, 0.98757873]]])

In [92]:
# Delete the array
arr5 = np.delete(arr4, 0, axis=1)

In [93]:
arr5

array([[[0.15947197, 0.17864396, 0.1677207 ]],

       [[0.02734588, 0.70156857, 0.28947575]],

       [[0.57935893, 0.43655231, 0.98757873]]])

In [94]:
np.save("new_array", arr5)

In [95]:
np.load("new_array.npy")

array([[[0.15947197, 0.17864396, 0.1677207 ]],

       [[0.02734588, 0.70156857, 0.28947575]],

       [[0.57935893, 0.43655231, 0.98757873]]])